### ISSUE TITLE
optional no color and light color scheme

### ISSUE THREAD

**Issue by unixhex** [yashbhutwala/kubectl-df-pv#11]
Nice plugin!
Unluckily it is impossible to read on a light or white background.

It would be nice to have either options and/or a configuration file
where one could switch to a _no color scheme_ (and optional to a color-scheme for light backgrounds).

![image](https://user-images.githubusercontent.com/3705369/88512982-b89e5280-cfe7-11ea-8a0d-363871e41f68.png)

**Comment by yashbhutwala** [comment]
@unixhex thanks for the input, I added a `--disable-color` flag in version [v0.2.6](https://github.com/yashbhutwala/kubectl-df-pv/releases/tag/v0.2.6).  So now you can invoke via:

```
kubectl df-pv -n dev -d
```
