### ISSUE TITLE
Can you specify the exact RBAC required

### ISSUE THREAD

**Issue by ketankr9** [yashbhutwala/kubectl-df-pv#15]
Can you specify the minimum RBAC required for accessing ```proxy/stats/summary``` k8s API?

**Comment by yashbhutwala** [comment]
Yup, @ketankr9 check out: https://github.com/yashbhutwala/kubectl-df-pv#requirements !!  If that's not clear enough, please free to send a PR.

**Comment by ketankr9** [comment]
Checked it already, it just says appropriate RBAC. I was hoping there would be definite permission narrower than cluster-admin.

**Comment by yashbhutwala** [comment]
"specifically, you need a service account with enough RBAC privileges to access api/v1/nodes/ from the kube-apiserver"... I didn't exactly explore what the yaml for that looks like, so you would have to play with the rbac yaml https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by ketankr9** [comment]
You are right @fabiorauber permission over resource `nodes/proxy` worked for me 👍 . Forgot to update this thread.
