### ISSUE TITLE
no Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by Ehekatl** [yashbhutwala/kubectl-df-pv#3]
can't use the plugin, did I miss something?

**Comment by yashbhutwala** [comment]
@Ehekatl can you provide a little bit more detail, as to the environment and the error you are seeing?

**Comment by yashbhutwala** [comment]
@Ehekatl this was fixed in https://github.com/yashbhutwala/kubectl-df-pv/releases/tag/v0.1.1 and I have a PR up for updating the plugin version in krew here: https://github.com/kubernetes-sigs/krew-index/pull/527

Meanwhile, give the latest version a try, and lemme know if it's fixed for you 😄

**Comment by Ehekatl** [comment]
@yashbhutwala works like a charm! Thanks for your work
