### ISSUE TITLE
Nothing is displayed (regular k8s + Rook Ceph with FlexVolumes)

### ISSUE THREAD

**Issue by guillaumedossantos** [yashbhutwala/kubectl-df-pv#4]
Is this supposed to work if I do not run kubectl proxy ?
Because https://gist.github.com/redmcg/60cfff7bca6f32969188008ad4a44c9a is not.
Following instructions on https://gist.github.com/redmcg/60cfff7bca6f32969188008ad4a44c9a#gistcomment-3192269 , I do not have any PvcRef on : curl -i $KUBEAPI/$node/proxy/stats/summary

What can I do?

**Comment by yashbhutwala** [comment]
@guillaumedossantos I have not tested with rook ceph flexVolumes.  This plugin doesn't require you to run kubectl proxy.  Perhaps, the volume provisioner, in this case rook, is not exposing those metrics to [`stats/summary`](https://github.com/yashbhutwala/kubectl-df-pv/blob/master/pkg/plugin/plugin.go#L117)

**Comment by yashbhutwala** [comment]
@guillaumedossantos thanks for taking the time to report this!  :100  As this is a storage provisioner issue, I'm closing it, please feel free to make a PR with docs or workaround if you find any.
