### ISSUE TITLE
Add a flag for the output to convert the resulting values into MB/GB/TB if possible

### ISSUE THREAD

**Issue by lbohnsac** [yashbhutwala/kubectl-df-pv#6]
Add a flag for the output to convert the resulting values into MB/GB/TB if possible.
It's already an awesome plug-in (one of my favorite ones)!
I think converting the bytes into MB/GB/TB shouldn't be really complex but will have a huge benefit for the users.

One more cosmetic thing:
Add a line break after "Searching PVCs so that the output starts on a new line.

I saw the colour defs in the code in root.go (50%/75%) that would be great to have it! Please activate it!

TIA

Cheers

**Comment by yashbhutwala** [comment]
Thanks for taking the time to create the issue! 💯  I'm glad you find it useful! 🎉  Both human readable format as well as coloring features are added as part of [v0.2.0](https://github.com/yashbhutwala/kubectl-df-pv/releases/tag/v0.2.0)
